# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: en

# Configuration for Rasa Core.
# Default policy was used.
# https://rasa.com/docs/rasa/core/policies/
policies:
  - name: MemoizationPolicy
  - name: RulePolicy
  - name: TEDPolicy
    max_history: 5
    epochs: 100
    constrain_similarities: true